- pkg/aws_config_client/completer.go
- pkg/aws_config_client/completer_test.go
To avoid having competing fields such as `source_profile` or `role_arn` from before the migration.
> [fix] Overwrite old aws config sections

- docs/serve-config.md
- pkg/aws_config_server/constants.go
- pkg/aws_config_server/list_roles.go
- pkg/aws_config_server/list_roles_test.go
- pkg/aws_config_server/shared_variables_test.go
We have some roles that are not meant to be consumed directly. Presenting these "hidden roles" to users makes it confusing for "non-experts". This tagging mechanism allows us to skip roles that are not meant for aws-oidc consumption.
> [feature] Give us the ability to skip roles

- README.md
- cmd/creds-process.go
- cmd/env.go
- cmd/env_test.go
- cmd/exec.go
- pkg/aws_config_client/parse_aws_config.go
- pkg/aws_config_client/parse_aws_config_test.go
- Instead of having to do `aws-oidc exec --client-id <asdfasdf> --issuer-url <asdfasdfa> --aws-role-arn <asdfasdf> -- cmd` we can now do `aws-oidc exec --profile <my profile> -- cmd`. Trade-off is we require that `<my profile>` be managed through `aws-oidc configure` so we can parse the necessary info.
- Profile names get calcualted in precedence order from:
1. use the `--profile` flag if provided
1. otherwise use the AWS_PROFILE env variable if provided
1. otherwise use the `default` profile
This should follow AWS SDK conventions.
> [breaking] Refactor env,exec to use --profile or AWS_PROFILE

- README.md
Changed README.md to recommend using `aws-oidc` command instead of `go run main.go`.
> [fix] Update README.md

- pkg/aws_config_client/completer.go
- pkg/aws_config_server/types.go
We weren't using the account alias everywhere/consistently
> [fix] Use the account alias when present everywhere

- cmd/configure.go
- pkg/aws_config_client/writers.go
- pkg/aws_config_client/writers_test.go
Instead of writing directly to the ~/.aws/config file, we write to a temporary file and then move it to the ~/.aws/config location. This helps prevent some category of race conditions where we have concurrent access to ~/.aws/config
> [fix] "Atomically" write aws config file

- pkg/aws_config_client/completer.go
- pkg/aws_config_client/completer_test.go
- pkg/aws_config_client/parse_aws_config.go
We already ran into an issue with this tty redirect hack (ruby on rails not running with a tty). Getting rid of it.
Note: should still be backwards-compatible with configs that have the tty redirect present.
> [fix] Get rid of the tty redirect hack

- pkg/aws_config_server/list_roles.go
- pkg/aws_config_server/list_roles_test.go
The `request-id` field prompted a flood of unique errors in our error reporting system, so I got rid of that unique identifier.
> [fix] reduce unique errors coming out of our AccessDenied error logging

- README.md
- cmd/serve-config.go
- pkg/aws_config_server/cache.go
- pkg/aws_config_server/list_roles.go
- pkg/aws_config_server/list_roles_test.go
- pkg/aws_config_server/webserver.go
One annoying thing about this feature is that you need `--` before the `skip-accts` feature. You'll have to use the flag like this: `--skip-accts=<acctName1>,<acctName2>`. We don't have to do this for the other fields: `web-server-port` and `concurrency`.
> [feature] add skip-accounts flag to serve-config

- .goreleaser.yml
Fixed according to this link: https://goreleaser.com/deprecations#brewsgithub
Haven't tested it yet. I'm hoping the CI checks in this PR will show if it works or not!
> [fix] update deprecated goreleaser tap setup

- cmd/serve-config.go
Use envconfig to require env variables. Without this the lack of these variables would lead to silent failures.
> require env variables for serve-config

- cmd/configure.go
- pkg/aws_config_client/completer.go
- pkg/aws_config_client/completer_test.go
Adds two new flags which allow setting the default region and role name
on the command line. When set, the user will not be prompted for those
inputs.
Fixes #166
> [feature] configure default regions and role on the command line

- .goreleaser.prerelease.yml
- .goreleaser.yml
Add support for M1 macs to release processes.
I was not able to test this, even for prereleases.
> release for darwin arm64

- Makefile
Both of these setup scripts were not supported anymore and deprecated. See the build errors [here](https://github.com/chanzuckerberg/aws-oidc/pull/180) for reference.  We should probably update these to use release-please instead.
> fix: broken setup scripts

- go.mod
- go.sum
updating go-misc and aws-mocks in one PR because they need to happen together.
> chore: upgrade go-misc and aws mocks

- go.mod
- go.sum
It appears that the [following
change](https://github.com/zalando/go-keyring/compare/v0.1.1...v0.2.0#diff-14c4aa5420de20b1ef5b174be7c1d389e4bdbbf71719ca66bf308caf38c60d1dR66-R93) in `zalando/go-keyring` is causing the problem described in #359. While we figure out how to fix this upstream, downgrade the version used in `aws-oidc` to stop breakages of new uses of `aws-oidc`.
Closes #359
> fix: Downgrade zalando/go-keyring to v0.1.1

- .github/workflows/release.yml
- .goreleaser.prerelease.yml
- .goreleaser.yml
I've been getting "no basic auth credentials" on my runs, and it's probably because I didn't include a docker login step. I added it to both release-please actions here.
I also got rid of the `trimpath` flag in the goreleaser release file and used the old "test" values from running `make release`
> fix: add docker login step to release actions

- go.mod
- go.sum
Dependabot bumped the version of go-keyring which breaks this application. This PR reverts that.
> fix: go-keyring downgrade

- .github/dependabot.yml
v0.2.0 has an open bug:
https://github.com/zalando/go-keyring/issues/80
And this dependency has been upgraded and then downgraded twice now. I propose that we just ignore the dependency completely until there's a known fix.
> chore: Prevent dependabot from upgrading broken dep

- .github/workflows/dependabot_automerge.yml
https://czi.atlassian.net/browse/CCIE-3911
This PR updates 'runs-on' in GitHub Actions workflow files to use direct values instead of label arrays.
> fix: Update runs-on labels in GitHub Actions workflows
